homeassistant:
  name: MyHome
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 78
  unit_system: metric
  time_zone: Europe/Bucharest
  customize: !include customize.yaml
  packages: !include_dir_named packages


### UI

http:
#  api_password: !secret http_password
#  server_port: 8123
#  trusted_networks: []
#  base_url: example.duckdns.org:8123
#  development: 1
frontend:
config:
history:
map:
logbook:


### LOGGING

logger:
  default: warning
  logs:
#    homeassistant.components.sensor.mitemp_bt: debug
    custom_components: debug
#    custom_components.sensor: warning
    rssdld: debug


### CONNECTION

#mqtt:
#  broker: !secret mqtt_server
#  port: !secret mqtt_port
#  username: !secret mqtt_username
#  password: !secret mqtt_password


### EXTRA COMPONENTS

# Discover some devices automatically
#discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:
# Cloud
cloud:
# Update HASS
updater:


### COMPONENTS

zone: !include include/zones.yaml

#group: !include include/groups.yaml
group: !include_dir_merge_named include/groups

sensor: !include include/sensors.yaml
media_player: !include include/media_players.yaml
device_tracker: !include include/device_trackers.yaml

panel_custom: !include include/panels.yaml
panel_iframe: !include include/iframes.yaml


history_graph:
  temperature:
    name: Temperature
    entities:
      - sensor.th_livingroom_temperature
      - sensor.th_bedroom_temperature
      - sensor.dark_sky_temperature
    hours_to_show: 72
  humidity:
    name: Humidity
    entities:
      - sensor.th_livingroom_humidity
      - sensor.th_bedroom_humidity
      - sensor.dark_sky_humidity
    hours_to_show: 72

#automation: !include include/automations.yaml

script: !include include/scripts.yaml
