# media center
- platform: kodi
  name: OSMC
  host: !secret kodi_host
  port: !secret kodi_port
  tcp_port: !secret kodi_port_vfs
  username: !secret kodi_username
  password: !secret kodi_password

# TVs  
- platform: samsungtv
  host: 192.168.1.22

- platform: panasonic_viera
  host: 192.168.1.23
