# media center
- platform: kodi
  host: http://192.168.1.21
  port: 8080
  name: OSMC
  username: osmc
  password: liviu22

# TVs  
- platform: samsungtv
  host: 192.168.1.22
- platform: panasonic_viera
  host: 192.168.1.23
